// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity3 = new Entity("Cube Entity")
engine.addEntity(cubeEntity3)
const cubeEntity3transform = new Transform({
  position: new Vector3(5.25, 1.25, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.5, 0.5, 2.25)
})
cubeEntity3.addComponentOrReplace(cubeEntity3transform)
const cubeEntity3boxShape = new BoxShape()
cubeEntity3.addComponentOrReplace(cubeEntity3boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity4 = new Entity("Cube Entity")
engine.addEntity(cubeEntity4)
const cubeEntity4transform = new Transform({
  position: new Vector3(3, 0, -0.666),
  rotation: new Quaternion(0, 0.258819, 0, 0.9659259),
  scale: new Vector3(1, 1, 1)
})
cubeEntity4.addComponentOrReplace(cubeEntity4transform)
const cubeEntity4boxShape = new BoxShape()
cubeEntity4.addComponentOrReplace(cubeEntity4boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity5 = new Entity("Cube Entity")
engine.addEntity(cubeEntity5)
const cubeEntity5transform = new Transform({
  position: new Vector3(2.362999, 0, 2.903),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
cubeEntity5.addComponentOrReplace(cubeEntity5transform)
const cubeEntity5boxShape = new BoxShape()
cubeEntity5.addComponentOrReplace(cubeEntity5boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

cubeEntity4.setParent(cubeEntity3)
cubeEntity5.setParent(cubeEntity4)



export let scene = {
}

