// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity3 = new Entity("Cube Entity")
engine.addEntity(cubeEntity3)
const cubeEntity3transform = new Transform({
  position: new Vector3(3.75, 0.75, 5.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
cubeEntity3.addComponentOrReplace(cubeEntity3transform)
const cubeEntity3boxShape = new BoxShape()
cubeEntity3.addComponentOrReplace(cubeEntity3boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity4 = new Entity("Cube Entity")
engine.addEntity(cubeEntity4)
const cubeEntity4transform = new Transform({
  position: new Vector3(10.25, 1, 10.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
cubeEntity4.addComponentOrReplace(cubeEntity4transform)
const cubeEntity4boxShape = new BoxShape()
cubeEntity4.addComponentOrReplace(cubeEntity4boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity5 = new Entity("Cube Entity")
engine.addEntity(cubeEntity5)
const cubeEntity5transform = new Transform({
  position: new Vector3(3.75, 1, 11.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
cubeEntity5.addComponentOrReplace(cubeEntity5transform)
const cubeEntity5boxShape = new BoxShape()
cubeEntity5.addComponentOrReplace(cubeEntity5boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity6 = new Entity("Cube Entity")
engine.addEntity(cubeEntity6)
const cubeEntity6transform = new Transform({
  position: new Vector3(10.5, 0.75, 5.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
cubeEntity6.addComponentOrReplace(cubeEntity6transform)
const cubeEntity6boxShape = new BoxShape()
cubeEntity6.addComponentOrReplace(cubeEntity6boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

