// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const defaultSphere2 = new Entity("Default Sphere")
engine.addEntity(defaultSphere2)
const defaultSphere2transform = new Transform({
  position: new Vector3(8, 2, 6),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
defaultSphere2.addComponentOrReplace(defaultSphere2transform)
const defaultSphere2sphereShape = new SphereShape()
defaultSphere2.addComponentOrReplace(defaultSphere2sphereShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const defaultCube1 = new Entity("Default Cube")
engine.addEntity(defaultCube1)
const defaultCube1transform = new Transform({
  position: new Vector3(8, 0.5, 3),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
defaultCube1.addComponentOrReplace(defaultCube1transform)
const defaultCube1boxShape = new BoxShape()
defaultCube1.addComponentOrReplace(defaultCube1boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

